// mockup/src/routes/login/+page.svelte
<!--
  Phase A4-β /login page.

  Visual reference: design_handoff_ferdinand/source/login.jsx (LoginV1 +
  LoginMobile) and design_handoff_ferdinand/screenshots/01-login.png.

  Route is in +layout.svelte's `fullscreenRoutes` (Phase A4-α) so the
  legacy cream chrome stays out of the way and the sketch-skin renders
  edge-to-edge. The page wraps its root in `.sketch-skin .grain` so all
  `var(--ink) / var(--paper) / var(--accent)` reads resolve to the
  kraft-paper palette in styles/tokens.css; if a future page wraps the
  same way it gets the same look without a CSS rewrite.

  Server contract: anki_server's `/api/auth/login` validates `username`
  as lowercase a-z 0-9 _ - (3..=64 chars) — NOT an email. The field is
  labelled "username" so the form can't lie about what the server
  accepts. Owl gaze tracking still keys off the field's character
  count exactly like the design (email empty → idle, focused/typing →
  pupils sweep -5 → +4 over the first 24 chars).
-->
<script lang="ts">
    import { onMount } from "svelte";
    import { browser } from "$app/environment";
    import { goto } from "$app/navigation";
    import { page } from "$app/stores";
    import { Btn, Field, Caption } from "$lib/components/ui";
    import {
        FerdinandMark,
        SketchOwl,
        SketchPlant,
        SketchSparkles,
        SketchUnderline,
        SketchArrow,
        SketchCheck,
        SketchUser,
        SketchLock,
        SketchGlobe,
    } from "$lib/components/sketch";
    import { auth } from "$lib/auth.svelte";

    // Form state — Svelte 5 runes mirror of the React `useOwl` hook.
    let username = $state("");
    let password = $state("");
    let usernameFocus = $state(false);
    let pwFocus = $state(false);
    let keepSignedIn = $state(true);
    let submitting = $state(false);
    let errorMessage = $state<string | null>(null);

    // Owl gaze derives from the username field, not the password — typing
    // the username should feel like the owl is reading along; password
    // focus closes its eyes (cute + privacy signal).
    const MAX = 24;
    let tracking = $derived(usernameFocus || username.length > 0);
    let t = $derived(Math.min(username.length / MAX, 1));
    let gazeX = $derived(tracking ? -5 + t * 9 : 0);
    let gazeY = $derived(tracking ? 2 : 0);
    let owlClosed = $derived(pwFocus);

    // Server endpoint hint. SSR-safe — falls back to a placeholder so the
    // page hydrates without flashing the wrong host. The field is
    // readonly because anki_server is bound to whatever origin the user
    // landed on; offering an editable input here would be a lie.
    let serverHint = $state("loading…");
    onMount(() => {
        serverHint = window.location.origin;
        // Already authed (e.g. user typed /login while signed in) — bounce
        // to next or home so they don't sit on a redundant login form.
        if (auth.status === "authed") {
            void goto(decodeNext($page.url.searchParams.get("next")));
        }
    });

    // The route guard never lets the user land on /login while authed,
    // but a successful submit still needs the same `next` decoder so the
    // post-login redirect lands them where they tried to go.
    function decodeNext(raw: string | null): string {
        if (!raw) return "/";
        // Reject open-redirect attempts: only allow same-origin paths
        // starting with a single `/` (and not `//host` schemeless URLs).
        if (!raw.startsWith("/") || raw.startsWith("//")) return "/";
        return raw;
    }

    async function onSubmit(event: Event) {
        event.preventDefault();
        if (submitting) return;
        errorMessage = null;
        const trimmedUser = username.trim();
        if (!trimmedUser || !password) {
            errorMessage = "username and password required";
            return;
        }
        submitting = true;
        try {
            await auth.login(trimmedUser, password);
            const next = decodeNext($page.url.searchParams.get("next"));
            await goto(next);
        } catch (err) {
            const raw = err instanceof Error ? err.message : "login failed";
            errorMessage = humaniseAuthError(raw);
        } finally {
            submitting = false;
        }
    }

    // Server surfaces "<status> <message>" via api.ts's jsonRequest. Strip
    // the leading status code so the inline caption reads like a sentence,
    // and lowercase to match the rest of the sketch typography.
    function humaniseAuthError(raw: string): string {
        const stripped = raw.replace(/^\d{3}\s+/, "").trim();
        if (!stripped) return "login failed";
        return stripped.toLowerCase();
    }
</script>

<svelte:head>
    <title>Sign in · Ferdinand</title>
</svelte:head>

<div class="sketch-skin grain login-root" data-testid="login-root">
    <!-- Desktop split (≥1024). Self-hides on phone via media queries. -->
    <div class="login-desktop">
        <!-- LEFT — illustration panel -->
        <aside class="login-art">
            <div class="logo-mark">
                <FerdinandMark size={36} />
                <div class="logo-text">
                    <div class="logo-name mono">Ferdinand</div>
                    <div class="logo-sub mono">SPACED · REPETITION</div>
                </div>
            </div>

            <div class="art-stage">
                <div class="art-sparkle"><SketchSparkles /></div>
                <SketchOwl size={220} closed={owlClosed} />
                <div class="art-plant"><SketchPlant size={120} /></div>

                <div class="art-headline">
                    <h1>
                        Quiet pages,<br />
                        <span class="headline-underlined">
                            long memory.
                            <span class="headline-underline">
                                <SketchUnderline width={210} />
                            </span>
                        </span>
                    </h1>
                    <p>
                        A single-user Anki rebuild. Local first, sync
                        optional, no add-ons, no AnkiWeb. Your collection
                        lives on your own server.
                    </p>
                </div>
            </div>

            <div class="art-foot mono">
                <span>→ rust core</span>
                <span>→ fsrs scheduler</span>
                <span>→ sveltekit</span>
            </div>
        </aside>

        <!-- RIGHT — form -->
        <section class="login-form-pane">
            <form class="login-form" onsubmit={onSubmit} novalidate>
                <Caption>session 01</Caption>
                <h2 class="form-title">sign in</h2>
                <p class="form-sub">Connect to your Ferdinand sync server.</p>

                <Field
                    label="Server"
                    value={serverHint}
                    readonly
                    mono
                    hint="Where your collection lives."
                >
                    {#snippet leading()}<SketchGlobe />{/snippet}
                </Field>

                <Field
                    label="Username"
                    bind:value={username}
                    placeholder="ktwu"
                    autocomplete="username"
                    name="username"
                    id="login-username"
                    onfocus={() => (usernameFocus = true)}
                    onblur={() => (usernameFocus = false)}
                >
                    {#snippet leading()}<SketchUser />{/snippet}
                </Field>

                <Field
                    label="Password"
                    type="password"
                    bind:value={password}
                    placeholder="••••••••••"
                    autocomplete="current-password"
                    name="password"
                    id="login-password"
                    onfocus={() => (pwFocus = true)}
                    onblur={() => (pwFocus = false)}
                >
                    {#snippet leading()}<SketchLock />{/snippet}
                </Field>

                <label class="keep-row mono">
                    <input
                        type="checkbox"
                        bind:checked={keepSignedIn}
                        class="keep-checkbox"
                    />
                    <span class="keep-icon"><SketchCheck size={18} /></span>
                    keep this device signed in
                </label>

                {#if errorMessage}
                    <div class="error-line mono" role="alert" data-testid="login-error">
                        // {errorMessage}
                    </div>
                {/if}

                <div class="cta-row">
                    <Btn
                        kind="primary"
                        size="lg"
                        type="submit"
                        disabled={submitting}
                        data-testid="login-submit"
                    >
                        {#snippet trailing()}<SketchArrow />{/snippet}
                        {submitting ? "signing in…" : "sign in"}
                    </Btn>
                    <button type="button" class="local-link mono" disabled aria-disabled="true">
                        run local-only
                    </button>
                </div>

                <div class="foot-meta mono">
                    <span>v0.1.0 · selfhost</span>
                    <span>NO TELEMETRY</span>
                </div>
            </form>
        </section>
    </div>

    <!-- Mobile (≤640). Mirrors LoginMobile — stacked, owl above form. -->
    <div class="login-mobile">
        <header class="m-header">
            <div class="logo-mark">
                <FerdinandMark size={32} />
                <div class="logo-text">
                    <div class="logo-name mono">Ferdinand</div>
                    <div class="logo-sub mono">SPACED · REPETITION</div>
                </div>
            </div>
        </header>
        <div class="m-owl">
            <div class="m-sparkle"><SketchSparkles /></div>
            <SketchOwl size={160} {gazeX} {gazeY} closed={owlClosed} />
        </div>
        <form class="login-form m-form" onsubmit={onSubmit} novalidate>
            <Caption>session 01</Caption>
            <h2 class="form-title">sign in</h2>
            <p class="form-sub">connect to your sync server.</p>

            <Field label="Server" value={serverHint} readonly mono>
                {#snippet leading()}<SketchGlobe />{/snippet}
            </Field>
            <Field
                label="Username"
                bind:value={username}
                placeholder="ktwu"
                autocomplete="username"
                onfocus={() => (usernameFocus = true)}
                onblur={() => (usernameFocus = false)}
            >
                {#snippet leading()}<SketchUser />{/snippet}
            </Field>
            <Field
                label="Password"
                type="password"
                bind:value={password}
                placeholder="••••••••••"
                autocomplete="current-password"
                onfocus={() => (pwFocus = true)}
                onblur={() => (pwFocus = false)}
            >
                {#snippet leading()}<SketchLock />{/snippet}
            </Field>

            {#if errorMessage}
                <div class="error-line mono" role="alert">// {errorMessage}</div>
            {/if}

            <Btn
                kind="primary"
                size="lg"
                type="submit"
                disabled={submitting}
                block
            >
                {#snippet trailing()}<SketchArrow />{/snippet}
                {submitting ? "signing in…" : "sign in"}
            </Btn>

            <div class="m-foot mono">
                <span>v0.1.0</span>
                <span>SELFHOSTED · NO TELEMETRY</span>
            </div>
        </form>
    </div>

    <!-- corner build tag -->
    <div class="corner-tag mono" aria-hidden="true">[ FERDINAND // M4 SYNC ]</div>
</div>

<style>
    .login-root {
        position: relative;
        min-height: 100vh;
        min-height: 100dvh;
        background: var(--bg);
        color: var(--ink);
        overflow-x: hidden;
    }

    /* Desktop split — visible ≥641px, hidden on phone. */
    .login-desktop {
        display: grid;
        grid-template-columns: 46% 1fr;
        min-height: 100vh;
        min-height: 100dvh;
    }
    @media (max-width: 640px) {
        .login-desktop {
            display: none;
        }
    }

    .login-art {
        position: relative;
        background: var(--bg-soft);
        border-right: 1.5px solid var(--ink);
        padding: 56px 64px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }
    .logo-mark {
        display: inline-flex;
        align-items: center;
        gap: 10px;
    }
    .logo-text {
        display: flex;
        flex-direction: column;
        line-height: 1;
    }
    .logo-name {
        font-size: 18px;
        font-weight: 600;
        letter-spacing: 0.02em;
    }
    .logo-sub {
        font-size: 10px;
        letter-spacing: 0.18em;
        color: var(--ink-mute);
        margin-top: 4px;
    }
    .art-stage {
        position: relative;
    }
    .art-sparkle {
        position: absolute;
        top: -28px;
        left: -8px;
        color: var(--accent);
    }
    .art-plant {
        position: absolute;
        right: 40px;
        top: 30px;
    }
    .art-headline {
        margin-top: 28px;
        max-width: 460px;
    }
    .art-headline h1 {
        font-family: var(--font-mono);
        font-weight: 500;
        font-size: 34px;
        line-height: 1.2;
        letter-spacing: -0.01em;
        margin: 0;
    }
    .headline-underlined {
        position: relative;
    }
    .headline-underline {
        position: absolute;
        left: 0;
        bottom: -10px;
    }
    .art-headline p {
        margin-top: 28px;
        font-size: 15px;
        color: var(--ink-soft);
        line-height: 1.6;
        max-width: 420px;
    }
    .art-foot {
        font-size: 11px;
        color: var(--ink-mute);
        letter-spacing: 0.1em;
        display: flex;
        gap: 16px;
    }

    .login-form-pane {
        padding: 72px 88px;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    .login-form {
        max-width: 380px;
        width: 100%;
    }
    .form-title {
        font-family: var(--font-mono);
        font-weight: 600;
        font-size: 28px;
        margin: 12px 0 6px;
    }
    .form-sub {
        color: var(--ink-soft);
        font-size: 14px;
        margin-bottom: 36px;
    }

    .keep-row {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 28px;
        margin-top: 8px;
        font-size: 12px;
        color: var(--ink-soft);
        letter-spacing: 0.04em;
        cursor: pointer;
        user-select: none;
    }
    /* Hide the native checkbox visually but keep it focusable so keyboard
       users can still toggle the preference. The SketchCheck icon is the
       visible affordance — its filled/empty state isn't synced (single-
       user honour-system flag) so the icon stays as-is. */
    .keep-checkbox {
        position: absolute;
        opacity: 0;
        width: 1px;
        height: 1px;
        pointer-events: none;
    }
    .keep-icon {
        display: inline-flex;
    }

    .error-line {
        font-size: 12px;
        color: var(--accent-warm, #b3461d);
        letter-spacing: 0.04em;
        margin: -8px 0 16px;
    }

    .cta-row {
        display: flex;
        align-items: center;
        gap: 14px;
    }
    .local-link {
        background: none;
        border: 0;
        font: inherit;
        font-family: var(--font-mono);
        font-size: 12px;
        color: var(--ink-soft);
        text-decoration: underline;
        text-underline-offset: 4px;
        letter-spacing: 0.04em;
        cursor: not-allowed;
        opacity: 0.55;
    }
    .foot-meta {
        display: flex;
        justify-content: space-between;
        font-size: 10px;
        color: var(--ink-mute);
        letter-spacing: 0.1em;
        padding-top: 24px;
        border-top: 1px dashed var(--rule);
        margin-top: 24px;
    }

    /* Mobile stack — visible ≤640px, hidden on desktop. */
    .login-mobile {
        display: none;
    }
    @media (max-width: 640px) {
        .login-mobile {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            min-height: 100dvh;
            padding: 56px 28px 32px;
        }
    }
    .m-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .m-owl {
        margin-top: 32px;
        position: relative;
        display: flex;
        justify-content: center;
    }
    .m-sparkle {
        position: absolute;
        top: 0;
        right: 24px;
        color: var(--accent);
    }
    .m-form {
        margin-top: 16px;
        max-width: none;
    }
    .m-foot {
        margin-top: auto;
        padding-top: 24px;
        display: flex;
        justify-content: space-between;
        border-top: 1px dashed var(--rule);
        font-size: 10px;
        color: var(--ink-mute);
        letter-spacing: 0.14em;
    }

    .corner-tag {
        position: absolute;
        top: 18px;
        right: 24px;
        font-size: 10px;
        color: var(--ink-mute);
        letter-spacing: 0.18em;
        pointer-events: none;
    }
    @media (max-width: 640px) {
        .corner-tag {
            top: 12px;
            right: 16px;
        }
    }
</style>

// design_handoff_ferdinand/source/login.jsx
/* Login screen — Ferdinand
   Variations:
   v1  split layout: sketch panel left, form right
   v2  centered single-column with sketch above form
   Mobile: condensed centered version

   Owl interaction (TunnelBear-inspired):
   - Email input → owl pupils track character count (gaze 0..1 → -1..+1)
   - Password input focus → owl closes eyes
*/

const { useState: _useStateLogin, useRef: _useRefLogin } = React;

/* A "watched" field that reports its value/focus to the owl.
   Identical UX to <Field> but controlled. */
const WatchField = ({ label, hint, leading, placeholder, type = "text", mono = false, optional, value, onChange, onFocus, onBlur }) => (
  <label style={{ display: "block", marginBottom: 18 }}>
    <div style={{
      fontFamily: '"JetBrains Mono", monospace',
      fontSize: 11, letterSpacing: "0.1em", textTransform: "uppercase",
      color: "var(--ink-soft)", marginBottom: 8,
      display: "flex", justifyContent: "space-between",
    }}>
      <span>{label}</span>
      {optional && <span style={{ color: "var(--ink-mute)", textTransform: "none", letterSpacing: "0.04em" }}>{optional}</span>}
    </div>
    <div style={{ display: "flex", alignItems: "center", gap: 10, borderBottom: "1.5px solid var(--ink)", paddingBottom: 8 }}>
      {leading && <span style={{ color: "var(--ink-soft)", display: "flex" }}>{leading}</span>}
      <input
        type={type}
        value={value}
        onChange={(e) => onChange && onChange(e.target.value)}
        onFocus={onFocus}
        onBlur={onBlur}
        placeholder={placeholder}
        style={{
          flex: 1, border: "none", outline: "none", background: "transparent",
          color: "var(--ink)",
          fontFamily: mono ? '"JetBrains Mono", monospace' : '"Geist", sans-serif',
          fontSize: 15, padding: "4px 0",
        }}
      />
    </div>
    {hint && <div style={{ fontSize: 12, color: "var(--ink-mute)", marginTop: 6, fontFamily: '"JetBrains Mono", monospace' }}>{hint}</div>}
  </label>
);

/* Compute owl gaze:
   - Idle (email empty, not focused): pupils rest at center (gazeX=0, gazeY=0)
   - Email focused or has text: pupils glance down-left (-5, +2) at the start of typing,
     sweep linearly to (+5, +2) as the field fills toward MAX chars.
   - Password focused: eyes close (no sockets, just lids).
*/
const useOwl = () => {
  const [email, setEmail] = _useStateLogin("");
  const [password, setPassword] = _useStateLogin("");
  const [emailFocus, setEmailFocus] = _useStateLogin(false);
  const [pwFocus, setPwFocus] = _useStateLogin(false);
  const MAX = 24;
  const tracking = emailFocus || email.length > 0;
  const t = Math.min(email.length / MAX, 1);
  const gazeX = tracking ? -5 + t * 9 : 0;
  const gazeY = tracking ? 2 : 0;
  return {
    email, password, pwFocus,
    onEmailChange: setEmail,
    onEmailFocus: () => setEmailFocus(true),
    onEmailBlur: () => setEmailFocus(false),
    onPwChange: setPassword,
    onPwFocus: () => setPwFocus(true),
    onPwBlur: () => setPwFocus(false),
    gazeX, gazeY, closed: pwFocus,
  };
};

const LogoMark = () => (
  <div style={{ display: "inline-flex", alignItems: "center", gap: 10 }}>
    <FerdinandMark size={36} />
    <div style={{ display: "flex", flexDirection: "column", lineHeight: 1 }}>
      <div className="mono" style={{ fontSize: 18, fontWeight: 600, letterSpacing: "0.02em" }}>Ferdinand</div>
      <div className="mono" style={{ fontSize: 10, letterSpacing: "0.18em", color: "var(--ink-mute)", marginTop: 4 }}>
        SPACED · REPETITION
      </div>
    </div>
  </div>
);

const FootMeta = () => (
  <div className="mono" style={{
    display: "flex", justifyContent: "space-between",
    fontSize: 10, color: "var(--ink-mute)", letterSpacing: "0.1em",
    paddingTop: 24,
    borderTop: "1px dashed var(--rule)",
    marginTop: 24,
  }}>
    <span>v0.1.0 · selfhost</span>
    <span>NO TELEMETRY</span>
  </div>
);

/* — VARIATION 1 ——————————————————————————————————— */
const LoginV1 = ({ width = 1280, height = 880 }) => {
  const o = useOwl();
  return (
  <div className="theme grain" style={{ width, height, display: "flex", overflow: "hidden", position: "relative" }}>
    {/* LEFT — illustration panel */}
    <div style={{
      flex: "0 0 46%",
      background: "var(--bg-soft)",
      borderRight: "1.5px solid var(--ink)",
      padding: "56px 64px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      position: "relative",
    }}>
      <LogoMark />

      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: -28, left: -8, color: "var(--accent)" }}>
          <SketchSparkles />
        </div>
        {/* Desktop: pupils stay still — owl is on the side, not above the form,
            so directional tracking doesn't read naturally. Mobile keeps tracking. */}
        <SketchOwl size={220} closed={o.closed} />
        <div style={{ position: "absolute", right: 40, top: 30 }}>
          <SketchPlant size={120} />
        </div>
        <div style={{ marginTop: 28, maxWidth: 460 }}>
          <h1 style={{
            fontFamily: '"JetBrains Mono", monospace',
            fontWeight: 500,
            fontSize: 34,
            lineHeight: 1.2,
            letterSpacing: "-0.01em",
            margin: 0,
          }}>
            Quiet pages,<br />
            <span style={{ position: "relative" }}>
              long memory.
              <span style={{ position: "absolute", left: 0, bottom: -10 }}>
                <SketchUnderline width={210} />
              </span>
            </span>
          </h1>
          <p style={{
            marginTop: 28,
            fontSize: 15,
            color: "var(--ink-soft)",
            lineHeight: 1.6,
            maxWidth: 420,
          }}>
            A single-user Anki rebuild. Local first, sync optional, no add-ons,
            no AnkiWeb. Your collection lives on your own server.
          </p>
        </div>
      </div>

      <div className="mono" style={{ fontSize: 11, color: "var(--ink-mute)", letterSpacing: "0.1em" }}>
        <span style={{ marginRight: 16 }}>→ rust core</span>
        <span style={{ marginRight: 16 }}>→ fsrs scheduler</span>
        <span>→ sveltekit</span>
      </div>
    </div>

    {/* RIGHT — form */}
    <div style={{ flex: 1, padding: "72px 88px", display: "flex", flexDirection: "column", justifyContent: "center" }}>
      <div style={{ maxWidth: 380 }}>
        <Caption>// session 01</Caption>
        <h2 style={{
          fontFamily: '"JetBrains Mono", monospace',
          fontWeight: 600,
          fontSize: 28,
          margin: "12px 0 6px",
        }}>Sign in</h2>
        <p style={{ color: "var(--ink-soft)", fontSize: 14, marginBottom: 36 }}>
          Connect to your Ferdinand sync server.
        </p>

        <Field label="Server" leading={<SketchGlobe />} value="sync.ktwu.dev" mono hint="Where your collection lives." />
        <WatchField label="Email" leading={<SketchMail />} placeholder="you@domain.com" value={o.email} onChange={o.onEmailChange} onFocus={o.onEmailFocus} onBlur={o.onEmailBlur} />
        <WatchField label="Password" leading={<SketchLock />} type="password" placeholder="••••••••••"
          value={o.password} onChange={o.onPwChange} onFocus={o.onPwFocus} onBlur={o.onPwBlur}
          optional={<a href="#" style={{ color: "var(--accent)", textDecoration: "none", fontSize: 11 }}>forgot?</a>} />

        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 28, marginTop: 8 }}>
          <SketchCheck size={18} />
          <span className="mono" style={{ fontSize: 12, color: "var(--ink-soft)", letterSpacing: "0.04em" }}>
            keep this device signed in
          </span>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
          <Btn kind="primary" size="lg" trailing={<SketchArrow />}>sign in</Btn>
          <a href="#" className="mono" style={{
            fontSize: 12, color: "var(--ink-soft)", textDecoration: "underline",
            textUnderlineOffset: 4, letterSpacing: "0.04em",
          }}>
            run local-only
          </a>
        </div>

        <FootMeta />
      </div>
    </div>

    {/* corner tag */}
    <div className="mono" style={{
      position: "absolute", top: 18, right: 24, fontSize: 10,
      color: "var(--ink-mute)", letterSpacing: "0.18em",
    }}>
      [ FERDINAND // M4 SYNC ]
    </div>
  </div>
);
};

/* — VARIATION 2 ——————————————————————————————————— */
const LoginV2 = ({ width = 1280, height = 880 }) => (
  <div className="theme grain" style={{
    width, height,
    display: "flex", alignItems: "center", justifyContent: "center",
    position: "relative", overflow: "hidden",
  }}>
    {/* scattered ambient sketches */}
    <div style={{ position: "absolute", top: 80, left: 80, opacity: 0.7 }}>
      <SketchPlant size={120} />
    </div>
    <div style={{ position: "absolute", bottom: 90, left: 140, opacity: 0.55 }}>
      <SketchBook size={140} />
    </div>
    <div style={{ position: "absolute", top: 110, right: 110, opacity: 0.6 }}>
      <SketchCardStack size={170} />
    </div>
    <div style={{ position: "absolute", bottom: 100, right: 90, opacity: 0.55 }}>
      <SketchCalendar size={110} />
    </div>

    <div style={{ position: "absolute", top: 32, left: 0, right: 0, display: "flex", justifyContent: "center" }}>
      <LogoMark />
    </div>

    {/* center card — index-card style */}
    <div style={{ width: 460, position: "relative" }}>
      <Panel offset={8}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 }}>
          <div>
            <Caption>{'// 01 — sign in'}</Caption>
            <h2 style={{
              fontFamily: '"JetBrains Mono", monospace',
              fontWeight: 600,
              fontSize: 26,
              margin: "10px 0 4px",
            }}>welcome back.</h2>
            <p className="mono" style={{ color: "var(--ink-soft)", fontSize: 12, letterSpacing: "0.04em", margin: 0 }}>
              {'>'} ready to review {'?'}
            </p>
          </div>
          <SketchLeaf size={40} />
        </div>

        <Field label="Server" leading={<SketchGlobe />} value="sync.ktwu.dev" mono />
        <Field label="Email" leading={<SketchMail />} placeholder="you@domain.com" />
        <Field label="Password" leading={<SketchLock />} type="password" placeholder="••••••••••" />

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 8 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <SketchCheck size={16} />
            <span className="mono" style={{ fontSize: 11, color: "var(--ink-soft)" }}>remember me</span>
          </div>
          <a href="#" className="mono" style={{ fontSize: 11, color: "var(--accent)", textDecoration: "none" }}>forgot password</a>
        </div>

        <div style={{ marginTop: 28, display: "flex", flexDirection: "column", gap: 12 }}>
          <Btn kind="primary" size="lg" trailing={<SketchArrow />} style={{ justifyContent: "center", width: "100%" }}>sign in</Btn>
          <Btn kind="outline" size="md" style={{ justifyContent: "center", width: "100%" }}>run local-only</Btn>
        </div>
      </Panel>

      <div className="hand" style={{
        position: "absolute", top: -36, right: -40,
        color: "var(--accent)", fontSize: 22, transform: "rotate(-8deg)",
      }}>
        single user. <br /> single laptop.
        <svg width="60" height="40" viewBox="0 0 60 40" className="sketch" style={{ color: "var(--accent)", marginTop: 4 }}>
          <path d="M50 4 C 30 14, 20 30, 10 36 M14 28 L 10 36 L 18 36" />
        </svg>
      </div>
    </div>

    <div className="mono" style={{
      position: "absolute", bottom: 28, left: 0, right: 0,
      display: "flex", justifyContent: "center", gap: 24,
      fontSize: 10, color: "var(--ink-mute)", letterSpacing: "0.18em",
    }}>
      <span>v0.1.0</span><span>·</span><span>SELFHOSTED</span><span>·</span><span>NO TELEMETRY</span>
    </div>
  </div>
);

/* — Mobile —————————————————————————————————————— */
const LoginMobile = ({ width = 390, height = 844 }) => {
  const o = useOwl();
  return (
  <div className="theme grain" style={{
    width, height, position: "relative", overflow: "hidden",
    padding: "56px 28px 32px",
    display: "flex", flexDirection: "column",
  }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
      <LogoMark />
      <SketchLeaf size={28} />
    </div>

    <div style={{ marginTop: 32, position: "relative", display: "flex", justifyContent: "center" }}>
      <SketchOwl size={160} gazeX={o.gazeX} gazeY={o.gazeY} closed={o.closed} />
      <div style={{ position: "absolute", top: 0, right: 24, color: "var(--accent)" }}>
        <SketchSparkles />
      </div>
    </div>

    <div style={{ marginTop: 16 }}>
      <Caption>{'// session 01'}</Caption>
      <h2 style={{
        fontFamily: '"JetBrains Mono", monospace',
        fontWeight: 600, fontSize: 22, margin: "6px 0 4px",
      }}>sign in</h2>
      <p style={{ fontSize: 13, color: "var(--ink-soft)", margin: "0 0 20px" }}>
        connect to your sync server.
      </p>

      <Field label="Server" leading={<SketchGlobe />} value="sync.ktwu.dev" mono />
      <WatchField label="Email" leading={<SketchMail />} placeholder="you@domain.com" value={o.email} onChange={o.onEmailChange} onFocus={o.onEmailFocus} onBlur={o.onEmailBlur} />
      <WatchField label="Password" leading={<SketchLock />} type="password" placeholder="••••••••••"
        value={o.password} onChange={o.onPwChange} onFocus={o.onPwFocus} onBlur={o.onPwBlur} />

      <Btn kind="primary" size="lg" trailing={<SketchArrow />} style={{ width: "100%", justifyContent: "center", marginTop: 12 }}>
        sign in
      </Btn>
      <Btn kind="ghost" size="md" style={{ width: "100%", justifyContent: "center", marginTop: 8 }}>
        run local-only
      </Btn>
    </div>

    <div className="mono" style={{
      marginTop: "auto", paddingTop: 24,
      display: "flex", justifyContent: "space-between",
      borderTop: "1px dashed var(--rule)",
      fontSize: 10, color: "var(--ink-mute)", letterSpacing: "0.14em",
    }}>
      <span>v0.1.0</span><span>SELFHOSTED · NO TELEMETRY</span>
    </div>
  </div>
);
};

Object.assign(window, { LoginV1, LoginV2, LoginMobile });
