// mockup/src/routes/stats/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { Caption } from "$lib/components/ui";
    import {
        fetchStatsRecent,
        fetchAnswerButtons,
        type ApiDayCount,
        type ApiAnswerButtons,
    } from "$lib/api";

    type Range = "1M" | "3M" | "1Y" | "ALL";
    const RANGE_DAYS: Record<Range, number> = {
        "1M": 30,
        "3M": 90,
        "1Y": 365,
        ALL: 365,
    };
    const RANGE_LABEL: Record<Range, string> = {
        "1M": "past 30 days",
        "3M": "past 90 days",
        "1Y": "past 365 days",
        ALL: "all time",
    };

    let range = $state<Range>("1M");

    let history = $state<ApiDayCount[] | null>(null);
    let answerButtons = $state<ApiAnswerButtons | null>(null);
    let loadError = $state<string | null>(null);
    let loaded = $state(false);

    async function load(days: number) {
        loadError = null;
        try {
            const [h, ab] = await Promise.all([
                fetchStatsRecent(days),
                fetchAnswerButtons(days),
            ]);
            history = h.history;
            answerButtons = ab;
        } catch (e) {
            history = [];
            answerButtons = { days, again: 0, hard: 0, good: 0, easy: 0 };
            loadError = e instanceof Error ? e.message : "Couldn't load stats";
        } finally {
            loaded = true;
        }
    }

    onMount(() => load(RANGE_DAYS[range]));

    function setRange(r: Range) {
        range = r;
        loaded = false;
        load(RANGE_DAYS[r]);
    }

    let values = $derived((history ?? []).map((d) => d.reviews));
    let totalReviews = $derived(values.reduce((a, v) => a + v, 0));
    let maxBar = $derived(Math.max(1, ...values));

    // Streak = consecutive non-zero days counted backwards from today.
    let streak = $derived.by(() => {
        let n = 0;
        for (let i = values.length - 1; i >= 0; i--) {
            if (values[i] > 0) n++;
            else break;
        }
        return n;
    });

    let activeDays = $derived(values.filter((v) => v > 0).length);
    let avgPerActiveDay = $derived(
        activeDays === 0 ? 0 : Math.round(totalReviews / activeDays),
    );
    let bestDay = $derived(values.length === 0 ? 0 : Math.max(...values));

    let answerEntries = $derived(
        answerButtons
            ? ([
                  ["again", answerButtons.again],
                  ["hard", answerButtons.hard],
                  ["good", answerButtons.good],
                  ["easy", answerButtons.easy],
              ] as const)
            : [],
    );
    let totalAns = $derived(answerEntries.reduce((a, [, v]) => a + v, 0));

    // Bar chart geometry — recomputed from the live history so the SVG
    // stays viewBox-correct across range changes. We render the chart at
    // a logical 520×140 viewBox and let CSS scale it; mobile shrinks the
    // visible width via aspect-ratio so the bars never run off screen.
    const CHART_W = 520;
    const CHART_H = 140;
    let barCount = $derived(Math.max(1, values.length));
    let barUnit = $derived((CHART_W - 14) / barCount);
    let bars = $derived(
        values.map((v, i) => {
            const x = i * barUnit + 4;
            const h = (v / maxBar) * (CHART_H - 8);
            return { x, h, w: Math.max(1, barUnit - 5), v };
        }),
    );

    // Activity heatmap — calendar-style grid (columns = weeks, rows =
    // Mon..Sun) built straight from the per-day history. Intensity is
    // bucketed against the busiest day in the window. Matches the design's
    // Heatmap (stats.jsx l. 74-119) but driven by real data instead of a
    // PRNG, and the column count follows the selected range.
    const HEAT_CELL = 15;
    const HEAT_GAP = 3;
    const HEAT_ROWS = 7;
    type HeatCell = {
        col: number;
        row: number;
        level: number;
        reviews: number;
        date: string;
    };
    function heatLevel(n: number, max: number): number {
        if (n <= 0) return 0;
        const r = n / max;
        if (r > 0.75) return 4;
        if (r > 0.5) return 3;
        if (r > 0.25) return 2;
        return 1;
    }
    // 0 = Monday … 6 = Sunday (ISO weekday order reads better as a grid).
    function isoDow(iso: string): number {
        return (new Date(`${iso}T00:00:00`).getDay() + 6) % 7;
    }
    let heatmap = $derived.by(() => {
        const days = history ?? [];
        if (days.length === 0) return { cols: 0, cells: [] as HeatCell[] };
        const max = Math.max(1, ...days.map((d) => d.reviews));
        const firstDow = isoDow(days[0].date);
        const cells: HeatCell[] = days.map((d, i) => {
            const idx = i + firstDow;
            return {
                col: Math.floor(idx / HEAT_ROWS),
                row: idx % HEAT_ROWS,
                level: heatLevel(d.reviews, max),
                reviews: d.reviews,
                date: d.date,
            };
        });
        const cols = Math.max(...cells.map((c) => c.col)) + 1;
        return { cols, cells };
    });
    let heatColors = [
        "var(--paper)",
        "color-mix(in oklch, var(--accent) 18%, var(--paper))",
        "color-mix(in oklch, var(--accent) 38%, var(--paper))",
        "color-mix(in oklch, var(--accent) 65%, var(--paper))",
        "var(--accent)",
    ];
</script>

<svelte:head><title>Stats — Ferdinand</title></svelte:head>

<div class="sketch-skin grain page sx-page" data-testid="stats-root">
    <header class="sx-head" data-testid="stats-head">
        <div class="sx-head-left">
            <Caption>the.ledger</Caption>
            <h1 class="sx-title mono" data-testid="stats-title">
                statistics
                <span class="sx-title-hand hand" aria-hidden="true">{RANGE_LABEL[range]}</span>
            </h1>
            <p class="sx-subtitle mono">all decks · snapshot of your review behavior</p>
        </div>
        <div class="sx-range" role="tablist" aria-label="time range" data-testid="stats-range">
            {#each ["1M", "3M", "1Y", "ALL"] as r (r)}
                <button
                    type="button"
                    role="tab"
                    aria-selected={range === r}
                    class="sx-range-pill mono"
                    class:active={range === r}
                    data-testid="stats-range-{r}"
                    onclick={() => setRange(r as Range)}
                >{r === "ALL" ? "all" : r}</button>
            {/each}
        </div>
    </header>

    {#if loadError}
        <div class="sx-error mono" role="alert" data-testid="stats-error">
            // couldn't reach server — {loadError}
        </div>
    {/if}

    <section class="sx-kpi-grid" data-testid="stats-kpi-grid">
        <article class="sx-tile" data-testid="stats-tile-reviews">
            <Caption>reviews</Caption>
            <div class="sx-tile-value mono">
                {totalReviews.toLocaleString()}<span class="sx-tile-unit">in {RANGE_DAYS[range]}d</span>
            </div>
        </article>
        <article class="sx-tile sx-tile-accent" data-testid="stats-tile-streak">
            <Caption>streak</Caption>
            <div class="sx-tile-value mono">
                {streak}<span class="sx-tile-unit">days</span>
            </div>
        </article>
        <article class="sx-tile" data-testid="stats-tile-avg">
            <Caption>avg / active day</Caption>
            <div class="sx-tile-value mono">
                {avgPerActiveDay.toLocaleString()}<span class="sx-tile-unit">cards</span>
            </div>
        </article>
        <article class="sx-tile" data-testid="stats-tile-best">
            <Caption>best day</Caption>
            <div class="sx-tile-value mono">
                {bestDay.toLocaleString()}<span class="sx-tile-unit">cards</span>
            </div>
        </article>
    </section>

    <section class="sx-charts" data-testid="stats-charts">
        <article class="sx-panel" data-testid="stats-bars-panel">
            <header class="sx-panel-head">
                <Caption>reviews per day</Caption>
                <span class="sx-panel-meta mono">last {RANGE_DAYS[range]}d</span>
            </header>
            {#if loaded && values.length === 0}
                <div class="sx-empty mono" data-testid="stats-bars-empty">
                    no reviews in this window.
                </div>
            {:else}
                <svg
                    class="sx-bars"
                    data-testid="stats-bars-svg"
                    viewBox="0 0 {CHART_W} {CHART_H + 26}"
                    preserveAspectRatio="none"
                    role="img"
                    aria-label="reviews per day"
                >
                    <line
                        x1="0"
                        y1={CHART_H}
                        x2={CHART_W}
                        y2={CHART_H}
                        stroke="var(--ink)"
                        stroke-width="1.4"
                    />
                    {#each [0.25, 0.5, 0.75] as p, i (i)}
                        <line
                            x1="0"
                            y1={CHART_H - CHART_H * p}
                            x2={CHART_W}
                            y2={CHART_H - CHART_H * p}
                            stroke="var(--rule)"
                            stroke-width="1"
                            stroke-dasharray="2 4"
                        />
                    {/each}
                    {#each bars as b, i (i)}
                        <rect
                            x={b.x}
                            y={CHART_H - b.h}
                            width={b.w}
                            height={b.h}
                            rx="1"
                            fill="var(--accent-soft)"
                            stroke="var(--ink)"
                            stroke-width="1"
                            data-testid="stats-bar-{i}"
                        />
                    {/each}
                    <text x="0" y={CHART_H + 18} class="sx-axis mono">{RANGE_DAYS[range]}d ago</text>
                    <text x={CHART_W - 36} y={CHART_H + 18} class="sx-axis mono">today</text>
                </svg>
            {/if}
        </article>

        <article class="sx-panel" data-testid="stats-answer-panel">
            <header class="sx-panel-head">
                <Caption>answer mix</Caption>
                <span class="sx-panel-meta mono">{totalAns} total</span>
            </header>
            {#if totalAns === 0}
                <div class="sx-empty mono" data-testid="stats-answer-empty">
                    no answers in this window.
                </div>
            {:else}
                <div class="sx-answer-list" data-testid="stats-answer-list">
                    {#each answerEntries as [k, v] (k)}
                        {@const pct = (v / totalAns) * 100}
                        <div class="sx-answer-row" data-testid="stats-answer-{k}">
                            <div class="sx-answer-head">
                                <span class="sx-answer-key sx-answer-key-{k} mono">{k}</span>
                                <span class="sx-answer-meta mono">{v} · {pct.toFixed(0)}%</span>
                            </div>
                            <div class="sx-answer-bar">
                                <div
                                    class="sx-answer-fill sx-answer-fill-{k}"
                                    style:width="{pct}%"
                                ></div>
                            </div>
                        </div>
                    {/each}
                </div>
            {/if}
        </article>
    </section>

    <section class="sx-heatmap-section" data-testid="stats-heatmap">
        <article class="sx-panel sx-heatmap-panel">
            <header class="sx-panel-head">
                <Caption>activity heatmap</Caption>
                <span class="sx-panel-meta mono">last {RANGE_DAYS[range]} days</span>
            </header>
            {#if loaded && heatmap.cells.length === 0}
                <div class="sx-empty mono" data-testid="stats-heatmap-empty">
                    no activity in this window.
                </div>
            {:else}
                <div class="sx-heatmap-grid-wrap">
                    <svg
                        class="sx-heatmap-grid"
                        data-testid="stats-heatmap-svg"
                        viewBox="0 0 {heatmap.cols * (HEAT_CELL + HEAT_GAP)} {HEAT_ROWS * (HEAT_CELL + HEAT_GAP)}"
                        width={heatmap.cols * (HEAT_CELL + HEAT_GAP)}
                        height={HEAT_ROWS * (HEAT_CELL + HEAT_GAP)}
                        role="img"
                        aria-label="daily review activity"
                    >
                        {#each heatmap.cells as c (c.date)}
                            <rect
                                x={c.col * (HEAT_CELL + HEAT_GAP)}
                                y={c.row * (HEAT_CELL + HEAT_GAP)}
                                width={HEAT_CELL}
                                height={HEAT_CELL}
                                rx="2"
                                fill={heatColors[c.level]}
                                stroke="var(--ink)"
                                stroke-width="0.9"
                                data-testid="stats-heat-{c.date}"
                            ><title>{c.date} · {c.reviews} review{c.reviews === 1 ? "" : "s"}</title></rect>
                        {/each}
                    </svg>
                </div>
                <div class="sx-heatmap-legend mono">
                    <span>{RANGE_DAYS[range]} days ago</span>
                    <span class="sx-heatmap-scale">
                        less
                        {#each heatColors as col, i (i)}
                            <span class="sx-heatmap-swatch" style:background={col}></span>
                        {/each}
                        more
                    </span>
                </div>
            {/if}
        </article>
    </section>
</div>

<style>
    .sx-page {
        max-width: 1100px;
        margin: 0 auto;
        padding: var(--space-8) var(--space-6) var(--space-12);
        display: flex;
        flex-direction: column;
        gap: var(--space-6);
    }

    /* ============== HEADER ============== */
    .sx-head {
        display: flex;
        justify-content: space-between;
        align-items: flex-end;
        flex-wrap: wrap;
        gap: var(--space-4);
    }
    .sx-head-left {
        display: flex;
        flex-direction: column;
        gap: 4px;
    }
    .sx-title {
        font-size: 28px;
        font-weight: 600;
        letter-spacing: -0.02em;
        margin: 4px 0 0;
        color: var(--ink);
        line-height: 1.05;
    }
    .sx-title-hand {
        font-family: var(--font-hand);
        color: var(--accent);
        font-size: 22px;
        margin-left: 12px;
        letter-spacing: 0;
        text-transform: lowercase;
    }
    .sx-subtitle {
        font-size: 12px;
        color: var(--ink-mute);
        margin: 4px 0 0;
        letter-spacing: 0.04em;
    }

    /* Range selector — paper pills, ink-bg + bg-fg when active. Matches
       design_handoff_ferdinand/source/stats.jsx range strip (l. 162-171). */
    .sx-range {
        display: inline-flex;
        gap: 6px;
        padding: 0;
    }
    .sx-range-pill {
        font-size: 11px;
        padding: 6px 12px;
        border: 1.2px solid var(--ink);
        border-radius: 4px;
        background: var(--paper);
        color: var(--ink-soft);
        letter-spacing: 0.06em;
        text-transform: lowercase;
        cursor: pointer;
        transition: background-color 100ms ease, color 100ms ease;
    }
    .sx-range-pill:hover {
        background: var(--bg-soft);
    }
    .sx-range-pill.active {
        background: var(--ink);
        color: var(--bg);
    }
    .sx-range-pill:focus-visible {
        outline: 2px solid var(--accent);
        outline-offset: 2px;
    }

    /* ============== ERROR BANNER ============== */
    .sx-error {
        padding: 10px 14px;
        border: 1.5px solid var(--due);
        background: color-mix(in oklch, var(--due) 10%, var(--paper));
        color: var(--due);
        border-radius: var(--radius-md);
        font-size: 12px;
    }

    /* ============== KPI TILES ============== */
    .sx-kpi-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 14px;
    }
    .sx-tile {
        background: var(--paper);
        border: 1.5px solid var(--ink);
        border-radius: var(--radius-md);
        box-shadow: var(--shadow-stamp-md);
        padding: 18px 20px;
    }
    .sx-tile-value {
        font-weight: 600;
        font-size: 36px;
        line-height: 1;
        letter-spacing: -0.02em;
        margin-top: 8px;
        color: var(--ink);
        font-variant-numeric: tabular-nums;
    }
    .sx-tile-accent .sx-tile-value {
        color: var(--accent);
    }
    .sx-tile-unit {
        font-size: 12px;
        font-weight: 400;
        color: var(--ink-mute);
        margin-left: 8px;
        letter-spacing: 0.02em;
    }

    /* ============== CHARTS ============== */
    .sx-charts {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 18px;
    }
    .sx-heatmap-section {
        display: block;
    }
    .sx-panel {
        background: var(--paper);
        border: 1.5px solid var(--ink);
        border-radius: var(--radius-md);
        box-shadow: var(--shadow-stamp-md);
        padding: 18px 22px;
        display: flex;
        flex-direction: column;
        gap: 12px;
    }
    .sx-heatmap-grid-wrap {
        display: flex;
        justify-content: center;
        padding: 4px 0;
    }
    .sx-heatmap-grid {
        display: block;
        max-width: 100%;
        height: auto;
    }
    .sx-heatmap-legend {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 10px;
        color: var(--ink-mute);
        letter-spacing: 0.04em;
    }
    .sx-heatmap-scale {
        display: inline-flex;
        align-items: center;
        gap: 4px;
    }
    .sx-heatmap-swatch {
        width: 11px;
        height: 11px;
        border-radius: 2px;
        border: 0.9px solid var(--ink);
        display: inline-block;
    }
    .sx-panel-head {
        display: flex;
        justify-content: space-between;
        align-items: baseline;
    }
    .sx-panel-meta {
        font-size: 11px;
        color: var(--ink-mute);
        letter-spacing: 0.04em;
    }
    .sx-empty {
        padding: 24px 0;
        text-align: center;
        font-size: 12px;
        color: var(--ink-mute);
        letter-spacing: 0.04em;
    }

    /* Bar chart — SVG fills container width; aspect-ratio keeps the
       138-unit drawing area visible while the 26-unit axis row is drawn
       below it. Mobile shrinks the chart height, never the bar count. */
    .sx-bars {
        width: 100%;
        height: auto;
        display: block;
        aspect-ratio: 520 / 166;
    }
    .sx-axis {
        font-family: var(--font-mono);
        font-size: 10px;
        fill: var(--ink-mute);
    }

    /* ============== ANSWER MIX ============== */
    .sx-answer-list {
        display: flex;
        flex-direction: column;
        gap: 12px;
    }
    .sx-answer-head {
        display: flex;
        justify-content: space-between;
        align-items: baseline;
        margin-bottom: 4px;
    }
    .sx-answer-key {
        font-size: 12px;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 0.08em;
    }
    .sx-answer-key-again {
        color: var(--due);
    }
    .sx-answer-key-hard {
        color: var(--warn);
    }
    .sx-answer-key-good {
        color: var(--accent);
    }
    .sx-answer-key-easy {
        color: var(--easy, #4a6c8e);
    }
    .sx-answer-meta {
        font-size: 11px;
        color: var(--ink-mute);
    }
    .sx-answer-bar {
        height: 10px;
        background: var(--bg-soft);
        border: 1px solid var(--ink);
        border-radius: 999px;
        overflow: hidden;
    }
    .sx-answer-fill {
        height: 100%;
        border-radius: 999px;
    }
    .sx-answer-fill-again {
        background: var(--due);
    }
    .sx-answer-fill-hard {
        background: var(--warn);
    }
    .sx-answer-fill-good {
        background: var(--accent);
    }
    .sx-answer-fill-easy {
        background: var(--easy, #4a6c8e);
    }

    /* ============== MOBILE (≤768px) ============== */
    @media (max-width: 768px) {
        .sx-page {
            padding: var(--space-5) var(--space-4) var(--space-10);
            gap: var(--space-5);
        }
        .sx-head {
            align-items: flex-start;
        }
        .sx-title {
            font-size: 22px;
        }
        .sx-title-hand {
            font-size: 18px;
            margin-left: 8px;
        }
        .sx-kpi-grid {
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
        }
        .sx-tile {
            padding: 12px 14px;
        }
        .sx-tile-value {
            font-size: 26px;
            margin-top: 4px;
        }
        .sx-tile-unit {
            font-size: 10px;
            margin-left: 4px;
        }
        .sx-charts {
            grid-template-columns: 1fr;
            gap: 12px;
        }
        .sx-panel {
            padding: 14px 16px;
        }
        .sx-bars {
            aspect-ratio: 520 / 200;
        }
    }
</style>

// design_handoff_ferdinand/source/stats.jsx
/* Stats — daily progress, retention, heatmap, deck breakdown */

const STATS_HERO = [
  { l: "streak", v: "14", u: "days", color: "var(--accent)" },
  { l: "retention", v: "91", u: "% · 30d", color: "var(--ink)" },
  { l: "reviewed", v: "1,284", u: "this month", color: "var(--ink)" },
  { l: "mature cards", v: "3,802", u: "of 5,412", color: "var(--ink)" },
];

/* Reviews per day — 30-day bar chart, deterministic */
const buildBars = () =>
  Array.from({ length: 30 }, (_, i) => {
    const seed = (i * 9301 + 49297) % 233280;
    const h = 28 + Math.round((seed / 233280) * 78);
    const dip = i % 7 === 6 ? 0.55 : 1; // Sunday-ish dip
    return { h: Math.round(h * dip), again: Math.round(h * dip * 0.18), good: Math.round(h * dip * 0.66) };
  });

const ReviewBars = ({ width = 520, height = 140 }) => {
  const bars = buildBars();
  const max = Math.max(...bars.map(b => b.h));
  const bw = (width - 14) / bars.length;
  return (
    <svg viewBox={`0 0 ${width} ${height + 30}`} width={width} height={height + 30} className="sketch" style={{ display: "block" }} aria-hidden="true">
      <line x1="0" y1={height} x2={width} y2={height} className="sketch" style={{ stroke: "var(--ink)" }} strokeWidth="1.4" />
      {[0.25, 0.5, 0.75].map((p, i) => (
        <line key={i} x1="0" y1={height - height * p} x2={width} y2={height - height * p}
              stroke="var(--rule)" strokeWidth="1" strokeDasharray="2 4" />
      ))}
      {bars.map((b, i) => {
        const x = i * bw + 4;
        const fullH = (b.h / max) * (height - 8);
        const goodH = (b.good / max) * (height - 8);
        return (
          <g key={i}>
            <rect x={x} y={height - fullH} width={bw - 5} height={fullH} fill="var(--accent-soft)" stroke="var(--ink)" strokeWidth="1" />
            <rect x={x} y={height - goodH} width={bw - 5} height={goodH} fill="var(--accent)" stroke="var(--ink)" strokeWidth="1" />
          </g>
        );
      })}
      <text x="0" y={height + 18} fontFamily="JetBrains Mono" fontSize="10" fill="var(--ink-mute)">apr 1</text>
      <text x={width / 2 - 14} y={height + 18} fontFamily="JetBrains Mono" fontSize="10" fill="var(--ink-mute)">apr 15</text>
      <text x={width - 38} y={height + 18} fontFamily="JetBrains Mono" fontSize="10" fill="var(--ink-mute)">apr 30</text>
    </svg>
  );
};

/* Retention curve */
const RetentionCurve = ({ width = 520, height = 140 }) => {
  const points = Array.from({ length: 30 }, (_, i) => {
    const seed = (i * 4783 + 12377) % 233280;
    const r = 0.78 + (seed / 233280) * 0.18;
    return { x: (i / 29) * (width - 4) + 2, y: height - (r - 0.7) * (height / 0.3) - 4 };
  });
  const path = points.map((p, i) => `${i === 0 ? "M" : "L"} ${p.x} ${p.y}`).join(" ");
  return (
    <svg viewBox={`0 0 ${width} ${height + 30}`} width={width} height={height + 30} className="sketch" style={{ display: "block" }} aria-hidden="true">
      <line x1="0" y1={height} x2={width} y2={height} stroke="var(--ink)" strokeWidth="1.4" />
      {[0.7, 0.8, 0.9, 1].map((p, i) => (
        <g key={i}>
          <line x1="0" y1={height - (p - 0.7) * (height / 0.3)} x2={width} y2={height - (p - 0.7) * (height / 0.3)}
                stroke="var(--rule)" strokeWidth="1" strokeDasharray="2 4" />
          <text x={width - 26} y={height - (p - 0.7) * (height / 0.3) - 3} fontFamily="JetBrains Mono" fontSize="9" fill="var(--ink-mute)">{Math.round(p * 100)}%</text>
        </g>
      ))}
      <path d={path} fill="none" stroke="var(--accent)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
      {points.filter((_, i) => i % 5 === 0).map((p, i) => (
        <circle key={i} cx={p.x} cy={p.y} r="2.4" fill="var(--paper)" stroke="var(--accent)" strokeWidth="1.2" />
      ))}
    </svg>
  );
};

/* Heatmap — 7x20 grid */
const Heatmap = ({ width = 520, rows = 7, cols = 20, cell = 18, gap = 4 }) => {
  const cells = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const seed = ((r * 31 + c * 17) * 9301 + 49297) % 233280;
      const v = (seed / 233280);
      let level = 0;
      if (v > 0.85) level = 4;
      else if (v > 0.6) level = 3;
      else if (v > 0.4) level = 2;
      else if (v > 0.2) level = 1;
      cells.push({ r, c, level });
    }
  }
  const colors = [
    "var(--paper)",
    "color-mix(in oklch, var(--accent) 18%, var(--paper))",
    "color-mix(in oklch, var(--accent) 38%, var(--paper))",
    "color-mix(in oklch, var(--accent) 65%, var(--paper))",
    "var(--accent)",
  ];
  const gridW = cols * (cell + gap);
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8, width }}>
      <div style={{ width: gridW, margin: "0 auto" }}>
        <svg viewBox={`0 0 ${gridW} ${rows * (cell + gap)}`} width={gridW} height={rows * (cell + gap)}>
          {cells.map(c => (
            <rect key={`${c.r}-${c.c}`}
              x={c.c * (cell + gap)} y={c.r * (cell + gap)}
              width={cell} height={cell} rx="2"
              fill={colors[c.level]}
              stroke="var(--ink)" strokeWidth="0.9" />
          ))}
        </svg>
      </div>
      <div style={{
        display: "flex", justifyContent: "space-between", alignItems: "center",
        fontFamily: '"JetBrains Mono", monospace', fontSize: 10, color: "var(--ink-mute)",
        width: gridW, margin: "0 auto",
      }}>
        <span>20 weeks ago</span>
        <span style={{ display: "flex", alignItems: "center", gap: 5 }}>
          less
          {colors.map((c, i) => (
            <span key={i} style={{ width: 11, height: 11, background: c, border: "1px solid var(--ink)", borderRadius: 2, display: "inline-block" }} />
          ))}
          more
        </span>
        <span>today</span>
      </div>
    </div>
  );
};

const HeroStat = ({ stat }) => (
  <div style={{
    flex: 1, padding: "20px 22px",
    background: "var(--paper)",
    border: "1.5px solid var(--ink)", borderRadius: 4,
    boxShadow: "3px 3px 0 var(--ink)",
  }}>
    <Caption>// {stat.l}</Caption>
    <div style={{
      fontFamily: '"JetBrains Mono", monospace', fontWeight: 600,
      fontSize: 38, lineHeight: 1, marginTop: 8, letterSpacing: "-0.02em",
      color: stat.color,
    }}>{stat.v}<span style={{ fontSize: 13, fontWeight: 400, color: "var(--ink-mute)", marginLeft: 6 }}>{stat.u}</span></div>
  </div>
);

const StatsV1 = ({ width = 1280, height = 880 }) => (
  <div className="theme grain" style={{ width, height, display: "flex", overflow: "hidden" }}>
    <NavRail />
    <main style={{ flex: 1, padding: "32px 48px", overflow: "auto", display: "flex", flexDirection: "column", gap: 24 }}>
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
        <div>
          <Caption>// the.ledger</Caption>
          <h1 style={{
            fontFamily: '"JetBrains Mono", monospace',
            fontSize: 28, fontWeight: 600, margin: "6px 0 0", letterSpacing: "-0.02em",
          }}>statistics
            <span className="hand" style={{ color: "var(--accent)", fontSize: 22, marginLeft: 12 }}>
              past 30 days
            </span>
          </h1>
        </div>
        <div style={{ display: "flex", gap: 6 }}>
          {["7d", "30d", "year", "all time"].map((p, i) => (
            <span key={p} className="mono" style={{
              fontSize: 11, padding: "6px 12px",
              border: "1.2px solid var(--ink)", borderRadius: 4,
              background: i === 1 ? "var(--ink)" : "var(--paper)",
              color: i === 1 ? "var(--bg)" : "var(--ink-soft)",
              letterSpacing: "0.06em",
              cursor: "pointer",
            }}>{p}</span>
          ))}
        </div>
      </header>

      <div style={{ display: "flex", gap: 14 }}>
        {STATS_HERO.map(s => <HeroStat key={s.l} stat={s} />)}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
        <div style={{
          background: "var(--paper)", border: "1.5px solid var(--ink)",
          borderRadius: 4, padding: "18px 22px", boxShadow: "3px 3px 0 var(--ink)",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
            <Caption>// reviews per day</Caption>
            <span className="mono" style={{ fontSize: 11, color: "var(--ink-mute)" }}>
              <span style={{ color: "var(--accent)" }}>■</span> good · <span style={{ color: "var(--accent-soft)" }}>■</span> total
            </span>
          </div>
          <ReviewBars width={520} />
        </div>
        <div style={{
          background: "var(--paper)", border: "1.5px solid var(--ink)",
          borderRadius: 4, padding: "18px 22px", boxShadow: "3px 3px 0 var(--ink)",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
            <Caption>// retention</Caption>
            <span className="mono" style={{ fontSize: 11, color: "var(--ink-mute)" }}>target 90%</span>
          </div>
          <RetentionCurve width={520} />
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1.4fr 1fr", gap: 20 }}>
        <div style={{
          background: "var(--paper)", border: "1.5px solid var(--ink)",
          borderRadius: 4, padding: "18px 22px", boxShadow: "3px 3px 0 var(--ink)",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
            <Caption>// activity heatmap</Caption>
            <span className="mono" style={{ fontSize: 11, color: "var(--ink-mute)" }}>140 days · 14d streak</span>
          </div>
          <Heatmap />
        </div>
        <div style={{
          background: "var(--paper)", border: "1.5px solid var(--ink)",
          borderRadius: 4, padding: "18px 22px", boxShadow: "3px 3px 0 var(--ink)",
        }}>
          <Caption>// answer distribution</Caption>
          <div style={{ marginTop: 14, display: "flex", flexDirection: "column", gap: 12 }}>
            {[
              { l: "again", v: 84,  pct: 12, c: "var(--due)" },
              { l: "hard",  v: 132, pct: 19, c: "var(--warn)" },
              { l: "good",  v: 412, pct: 59, c: "var(--accent)" },
              { l: "easy",  v: 71,  pct: 10, c: "var(--easy, #4a6c8e)" },
            ].map(d => (
              <div key={d.l}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 4 }}>
                  <span className="mono" style={{ fontSize: 12, fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.06em", color: d.c }}>{d.l}</span>
                  <span className="mono" style={{ fontSize: 11, color: "var(--ink-mute)" }}>{d.v} · {d.pct}%</span>
                </div>
                <div style={{ height: 10, background: "var(--bg-soft)", border: "1px solid var(--ink)", borderRadius: 999, overflow: "hidden" }}>
                  <div style={{ width: `${d.pct}%`, height: "100%", background: d.c }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div style={{
        background: "var(--paper)", border: "1.5px solid var(--ink)",
        borderRadius: 4, padding: "18px 22px", boxShadow: "3px 3px 0 var(--ink)",
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
          <Caption>// deck breakdown</Caption>
          <span className="mono" style={{ fontSize: 11, color: "var(--ink-mute)" }}>5 active decks</span>
        </div>
        <div className="mono" style={{
          display: "grid", gridTemplateColumns: "1.6fr 80px 80px 80px 1.2fr 80px",
          gap: 14, fontSize: 10, color: "var(--ink-mute)",
          textTransform: "uppercase", letterSpacing: "0.16em",
          padding: "8px 0", borderBottom: "1px dashed var(--rule)",
        }}>
          <span>deck</span><span style={{ textAlign: "right" }}>cards</span><span style={{ textAlign: "right" }}>mature</span><span style={{ textAlign: "right" }}>retention</span><span>activity</span><span style={{ textAlign: "right" }}>last</span>
        </div>
        {[
          { g: "JP", n: "日文 N2", c: 2340, m: 1820, r: 92, l: "today", a: 0.85 },
          { g: "RS", n: "Rust ownership", c: 412, m: 388, r: 96, l: "today", a: 0.55 },
          { g: "HX", n: "World History", c: 890, m: 712, r: 88, l: "1d", a: 0.42 },
          { g: "AN", n: "Anatomy", c: 1567, m: 824, r: 79, l: "2d", a: 0.6 },
          { g: "PT", n: "Piano theory", c: 203, m: 58, r: 84, l: "11d", a: 0.1 },
        ].map((d, i) => (
          <div key={d.n} style={{
            display: "grid", gridTemplateColumns: "1.6fr 80px 80px 80px 1.2fr 80px",
            gap: 14, alignItems: "center",
            padding: "12px 0",
            borderBottom: i === 4 ? "none" : "1px solid var(--rule-soft)",
            fontFamily: '"JetBrains Mono", monospace', fontSize: 12,
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <span style={{
                width: 26, height: 26, display: "grid", placeItems: "center",
                border: "1.2px solid var(--ink)", borderRadius: 3, fontSize: 9, fontWeight: 600,
                background: "var(--bg-soft)",
              }}>{d.g}</span>
              <span style={{ fontWeight: 500 }}>{d.n}</span>
            </div>
            <span style={{ textAlign: "right" }}>{d.c.toLocaleString()}</span>
            <span style={{ textAlign: "right", color: "var(--ink-soft)" }}>{d.m.toLocaleString()}</span>
            <span style={{ textAlign: "right", color: d.r >= 90 ? "var(--accent)" : "var(--warn)" }}>{d.r}%</span>
            <div style={{ height: 6, background: "var(--bg-soft)", border: "1px solid var(--ink)", borderRadius: 999, overflow: "hidden" }}>
              <div style={{ width: `${d.a * 100}%`, height: "100%", background: "var(--accent)" }} />
            </div>
            <span style={{ textAlign: "right", color: "var(--ink-mute)" }}>{d.l}</span>
          </div>
        ))}
      </div>
    </main>
  </div>
);

const StatsMobile = ({ width = 390, height = 844 }) => (
  <div className="theme grain" style={{ width, height, position: "relative", overflow: "hidden", display: "flex", flexDirection: "column" }}>
    <header style={{
      padding: "48px 22px 14px",
      borderBottom: "1.5px solid var(--ink)",
    }}>
      <Caption>// stats</Caption>
      <div className="mono" style={{ fontSize: 18, fontWeight: 600, marginTop: 4 }}>past 30 days</div>
    </header>

    <main style={{ flex: 1, overflow: "auto", padding: "16px 22px 96px", display: "flex", flexDirection: "column", gap: 16 }}>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
        {STATS_HERO.map(s => (
          <div key={s.l} style={{
            background: "var(--paper)", border: "1.4px solid var(--ink)",
            borderRadius: 4, padding: "12px 14px", boxShadow: "2px 2px 0 var(--ink)",
          }}>
            <Caption style={{ fontSize: 9 }}>// {s.l}</Caption>
            <div style={{
              fontFamily: '"JetBrains Mono", monospace', fontWeight: 600,
              fontSize: 22, marginTop: 4, color: s.color, lineHeight: 1,
            }}>{s.v}<span style={{ fontSize: 10, color: "var(--ink-mute)", fontWeight: 400, marginLeft: 4 }}>{s.u}</span></div>
          </div>
        ))}
      </div>

      <div style={{
        background: "var(--paper)", border: "1.4px solid var(--ink)",
        borderRadius: 4, padding: "14px 16px", boxShadow: "2px 2px 0 var(--ink)",
      }}>
        <Caption>// reviews per day</Caption>
        <div style={{ marginTop: 10 }}>
          <ReviewBars width={310} height={100} />
        </div>
      </div>

      <div style={{
        background: "var(--paper)", border: "1.4px solid var(--ink)",
        borderRadius: 4, padding: "14px 16px", boxShadow: "2px 2px 0 var(--ink)",
      }}>
        <Caption>// retention</Caption>
        <div style={{ marginTop: 10 }}>
          <RetentionCurve width={310} height={90} />
        </div>
      </div>

      <div style={{
        background: "var(--paper)", border: "1.4px solid var(--ink)",
        borderRadius: 4, padding: "14px 16px", boxShadow: "2px 2px 0 var(--ink)",
      }}>
        <Caption>// answer mix</Caption>
        <div style={{ marginTop: 10, display: "flex", flexDirection: "column", gap: 8 }}>
          {[
            { l: "again", v: 84, pct: 12, c: "var(--due)" },
            { l: "hard",  v: 132, pct: 19, c: "var(--warn)" },
            { l: "good",  v: 412, pct: 59, c: "var(--accent)" },
            { l: "easy",  v: 71, pct: 10, c: "var(--easy, #4a6c8e)" },
          ].map(d => (
            <div key={d.l}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}>
                <span className="mono" style={{ fontSize: 11, color: d.c, textTransform: "uppercase", letterSpacing: "0.06em", fontWeight: 500 }}>{d.l}</span>
                <span className="mono" style={{ fontSize: 10, color: "var(--ink-mute)" }}>{d.pct}%</span>
              </div>
              <div style={{ height: 8, background: "var(--bg-soft)", border: "1px solid var(--ink)", borderRadius: 999, overflow: "hidden" }}>
                <div style={{ width: `${d.pct}%`, height: "100%", background: d.c }} />
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>

    <nav style={{
      position: "absolute", bottom: 0, left: 0, right: 0,
      borderTop: "1.5px solid var(--ink)",
      background: "var(--bg-soft)",
      display: "grid", gridTemplateColumns: "repeat(4, 1fr)",
      padding: "8px 0 22px",
    }}>
      {[
        { i: <SketchBook size={22} />, l: "decks" },
        { i: <SketchCardStack size={22} />, l: "browse" },
        { i: <SketchPlus />, l: "add" },
        { i: <SketchCalendar size={22} />, l: "stats", on: true },
      ].map((it, i) => (
        <div key={i} style={{
          display: "flex", flexDirection: "column", alignItems: "center", gap: 4,
          color: it.on ? "var(--accent)" : "var(--ink-mute)",
        }}>
          {it.i}
          <span className="mono" style={{ fontSize: 9, letterSpacing: "0.1em", textTransform: "uppercase" }}>{it.l}</span>
        </div>
      ))}
    </nav>
  </div>
);

Object.assign(window, { StatsV1, StatsMobile });
